jfrog/jfrog-client-go

README.md
artifactory/manager.go
artifactory/services/delete.go
tests/utils.go

Fixes #18.
Matching pull request on jfrog-cli-go

Removed redundant DeleteItem interface

---

artifactory/services/go/publishzipandmod.go

This commit resolve JFrog-CLI issue #430

Go Publish : Calculate and add checksum headers to published files.

---

utils/utils.go
utils/utils_test.go

Fix .. (the parent directory) in upload pattern

---

utils/utils.go
utils/utils_test.go

Fix .. (the parent directory) in upload pattern

 Fix .. (the parent directory) in upload pattern. (#93)

---

README.md
artifactory/auth/rtdetails.go
artifactory/httpclient/rtClientBuilder.go
httpclient/clientBuilder.go

This add support for client certificates fixing #82.

Add support for client certificates.

---

README.md
artifactory/manager.go
artifactory/services/security.go
tests/artifactorysecurity_test.go
tests/jfrogclient_test.go
tests/utils.go

Enables access to the following Token APIs:
* Create Token
* Get Tokens
* Refresh Token
* Revoke Token

Implement Security Service

---

httpclient/client.go

https://github.com/jfrog/jfrog-cli/issues/597
The extraction path cannot be empty or ".".

Illegal file path error in download --explode

---

artifactory/auth/rtdetails.go
artifactory/manager.go
artifactory/services/version.go
auth/commondetails.go
distribution/auth/dsdetails.go
distribution/manager.go
distribution/services/version.go

Also:
Make GetVersion functions use a service.
Rename Wrong file #132

Add ssh authentication to service manager

---

README.md
bintray/manager.go
bintray/services/mavensync/mavensync.go
bintray/services/mavensync/mavensync_test.go

This resolves #148 via addition of MavenCentralSyncService
I tried to keep up with conventions in this repo, happy to make any adjustments if further alignment is needed

resolves #148 by adding MavenCentralSyncService

---

artifactory/services/props.go

Following [683](https://github.com/jfrog/jfrog-cli/issues/683) on JFrog CLI.

Fix Set-Props on artifact with special chars

---

README.md
distribution/manager.go
distribution/services/distribute.go
distribution/services/getstatus.go
distribution/services/getstatus_test.go
tests/distribution_test.go
tests/utils.go

* Add sync distribution: `distManager.DistributeReleaseBundleSync(params, maxWait)`
* Add get status service: `distManager.GetDistributionStatus(params)`
Related to: https://github.com/jfrog/jfrog-cli/pull/756

Add support for sync distribution

---

artifactory/services/utils/deleteutils.go
artifactory/services/utils/deleteutils_test.go
artifactory/services/utils/searchutil.go
artifactory/services/utils/tests/testdata/artifact_file_2.json
artifactory/services/utils/tests/testdata/buffer_file_ascending_order_4.json

Fixes https://github.com/jfrog/jfrog-cli/issues/808

Delete - Bugfix Incorrect filters for delete directories

---

artifactory/services/utils/searchutil.go

Fixes https://github.com/jfrog/jfrog-cli/issues/807

Bugfix - fail to copy files with the same prefix name

---

README.md
artifactory/services/upload.go
artifactory/services/utils/properties.go
artifactory/services/utils/properties_test.go

Fixes https://github.com/jfrog/jfrog-cli/issues/786

Add support for escaping of commas in upload command

---

artifactory/services/download.go
utils/io/fileutils/files.go
utils/io/fileutils/files_test.go
utils/io/fileutils/testdata/files/comparisonFile

Moved to support plugins PR on the CLI

Move comparison function to file utils

---

README.md
artifactory/emptymanager.go
artifactory/manager.go
artifactory/services/deleterepository.go
artifactory/services/getrepository.go
tests/artifactorylocalrepository_test.go
tests/artifactoryremoterepository_test.go
tests/artifactoryvirtualrepository_test.go
tests/utils.go

Add GetAllRepositories command to support delete repo by pattern.
Precondition for:
https://github.com/jfrog/jfrog-cli-core/pull/14
https://github.com/jfrog/jfrog-cli/pull/847

Add GetAllRepositories command

---

artifactory/emptymanager.go
artifactory/manager.go
artifactory/services/download.go
artifactory/services/upload.go
artifactory/services/utils/fileinfoutils.go
utils/io/content/contentreader.go

Related: https://github.com/jfrog/jfrog-cli-core/pull/23.

Added detailed summary support for upload command

---

artifactory/services/props.go
artifactory/services/utils/searchutil.go

Fixes https://github.com/jfrog/jfrog-cli/issues/669

Enable set/delete properties request to be non recursive

---

README.md
tests/artifactoryupload_test.go
tests/utils.go

Detailed summary for upload command - update README and tests 

---

README.md
artifactory/services/remoterepository.go
tests/artifactoryremoterepository_test.go

Xray index remote fix

---

appveyor.yml
httpclient/client.go

-----
* DownloadFileDetails - Change `LocalFileName` name to `FileName`.
* Make go vet running on all packages.

Fix go vet

---

artifactory/emptymanager.go

Update EmptyArtifactoryServicesManager struct

---

artifactory/buildinfo/buildinfo.go
artifactory/emptymanager.go
artifactory/manager.go
artifactory/services/buildinfo.go

Add Uri to GetBuildInfo

---

README.md
artifactory/emptymanager.go
artifactory/manager.go
artifactory/services/buildinfo.go

Support project name on build-info publish

---

artifactory/emptymanager.go

Compile time check of interface implementation by EmptyArtifactoryServicesManager

---

tests/artifactoryctx_test.go

Fixed go vet failure

---

artifactory/buildinfo/buildinfo.go

Add module type and checksums to support the build append command.
Related to:
https://github.com/jfrog/jfrog-cli/pull/844
https://github.com/jfrog/jfrog-cli-core/pull/12

Add module type to build info

---

artifactory/services/delete.go
artifactory/services/utils/deleteutils.go
artifactory/services/utils/deleteutils_test.go
artifactory/services/utils/tests/testdata/artifact_file_1.json
artifactory/services/utils/tests/testdata/buffer_file_ascending_order_3.json

Bugfix - upload sync-delete with special chars

---

artifactory/services/utils/tests/testdata/merged_buffer_ascending_order.json
artifactory/services/utils/tests/testdata/prebuffer_file.json

Fixed tests after PR #235

---

artifactory/services/utils/aqlquerybuilder.go

Change pypi AQL query to receive files query part as parameter

---

artifactory/buildinfo/buildinfo.go

Buildinfo: Support list of Vcs

---

artifactory/buildinfo/buildinfo.go
artifactory/services/discardBuilds.go
artifactory/services/discardBuilds_test.go
bintray/services/download.go
httpclient/client.go

-----
Follow-up https://github.com/jfrog/jfrog-client-go/pull/205

Unify time layout for builds

---

artifactory/services/download.go
artifactory/services/upload.go

Increse upload/download buffer size to 20000

---

artifactory/services/utils/artifactoryutils.go
artifactory/services/utils/searchutil.go

Remove duplicate items when performing search by build with dependencies

---

httpclient/client.go

-----
This fixes a bug which was introduced in the last release (0.17.0). The bug description is as follows:
When downloading an archive with the "explode" option, if the file is not downloaded into the current directory, the archive will fail. It will fail because the code looks for the archive in the current dir, rather than in the dir it was downloaded to.

Bug fix - Explode after download fails if not download path not curr dir

---

artifactory/services/utils/aqlquerybuilder.go

This reverts commit 49b146c48cfd83f171b8ed15b1cbb06c1751f099.
-----

Revert "Change pypi AQL query to receive files query part (#243)"

---

utils/archiveutils.go
utils/io/fileutils/files.go

Remove 'os.rename' from the codebase

---

utils/archiveutils.go
utils/io/fileutils/archive.go
utils/io/fileutils/files.go

Bugfix - explode fail to extract files with no r permissions 

---

artifactory/services/utils/searchutil.go

-----
Related PR:
* https://github.com/jfrog/jfrog-cli/pull/909
* https://github.com/jfrog/jfrog-cli-core/pull/39

Add GetProperty func

---

artifactory/services/dockerpromote.go

-----
Resolves https://github.com/jfrog/jfrog-cli/issues/891

Add success message to docker-promote

---

tests/utils.go

Change repositories' tests retry interval

---

artifactory/services/groups.go
artifactory/services/users.go

User management commands - fix error message text

---

artifactory/services/users.go

Change user's name to username in the csv parse tag

---

README.md
artifactory/emptymanager.go
artifactory/manager.go
artifactory/services/users.go

Added GetAllUsers functionality

---

artifactory/services/upload.go

-----
It was found that the Symlink Props was added by mistake to the entire file-group although they related only to a single file.

Fix SymlinkProps Bug

---

artifactory/buildinfo/buildinfo.go

Add 'requiredBy' field to buildinfo

---

artifactory/buildinfo/buildinfo.go
artifactory/services/upload.go
utils/git.go
utils/vcsdetails.go
utils/vcsdetails_test.go

VCS details: add new data member "branch"

---

artifactory/services/fspatterns/utils.go
artifactory/services/upload.go
artifactory/services/utils/specutils.go
bintray/services/upload.go
utils/utils.go
utils/utils_test.go

ant pattern

---

utils/utils.go

Ant pattern - fixing for Windows

---

utils/utils.go
utils/utils_test.go

Ant pattern fix test

---

README.md
artifactory/emptymanager.go
artifactory/manager.go
artifactory/services/permissiontarget.go
tests/artifactorypermissiontarget_test.go

-----
Following [jfrog/jfrog-cli#902](https://github.com/jfrog/jfrog-cli/issues/902)

Fix failure due to empty fields in permission target

---

artifactory/services/upload.go
tests/artifactorydownload_test.go
tests/artifactoryupload_test.go

Upload archive tests

---

README.md
artifactory/emptymanager.go
artifactory/manager.go

Fix name of return value

---

artifactory/services/utils/properties_test.go
distribution/services/utils/distributionutils.go

Props tests fixes

---

README.md
artifactory/emptymanager.go
artifactory/manager.go
artifactory/services/security.go
tests/artifactorysecurity_test.go

-----
Implements two changes
1. Change the anonymous struct inside GetTokensResponseData.
2. Implement a GetUserTokens lookup function to lookup tokens issued to a username.
I would like to implement some tests for the second item, but require some help around what is the best way to write a test case for function which doesn't take *Params as args.

Implement GetUserTokens lookup function

---

tests/artifactoryremoterepository_test.go

Fix remoteCreateWithParamTest test

---

utils/git.go

-----
Avoid returning an error, in case the latest git commit message could not be fetched from the local git repository. This PR aims to resolve https://github.com/jfrog/artifactory-azure-devops-extension/issues/239

Avoid failing, if latest commit message could not be fetched

---

distribution/manager.go
distribution/services/create.go
distribution/services/distribute.go
distribution/services/update.go
tests/distribution_test.go
tests/utils.go

Fix release bundle creation with dry-run

---

README.md
artifactory/services/promote.go

-----
Don't pass config_test.go for a pattern that does contain syntax errors but I'm not sure how it can be related to my edits

add FailFast option to Promote

---

distribution/services/getstatus.go

Fix unmarshalling error in distribution response

---

artifactory/services/download.go

-----
Fixes: https://github.com/jfrog/jfrog-cli/issues/653

Bugfix - TMP files don't get deleted after download

---

artifactory/services/remoterepository.go

fix: ContentSynchronisation json annotation

---

README.md
artifactory/services/permissiontarget.go
tests/artifactorypermissiontarget_test.go

-----
Addresses https://github.com/jfrog/jfrog-client-go/issues/336

return nil err when a permission target doesn't exist

---

README.md
artifactory/services/xrayscan.go
xray/manager.go
xray/services/policy.go
xray/services/scan.go
xray/services/utils/watchbody.go
xray/services/version.go
xray/services/watch.go

Add new Xray scan graph API

---

xray/services/scan.go

Bugfix- get scan graph result should returns 202 and not 201

---

config/configbuilder.go
xray/services/scan.go

Created a struct for impact paths

---

xray/services/scan.go

Print Vulnerabilities Table

---

artifactory/services/fspatterns/utils.go
artifactory/services/upload.go

Upload symlinks with their names

---

xray/services/scan.go

Xray scan table improvements

---

xray/services/scan.go

Update ScanResponse struct

---

artifactory/services/go/publishzipandmod.go

Detailed summary for gp - remove "api/go/" from target Path

---

utils/utils.go

v1: Fix: target url in  detailed-summary for maven and gradle

---

utils/utils.go

v2: Fix: target url in detailed-summary for maven and gradle

---

README.md

Readme updates (v1)

---

xray/services/scan.go

Fix Xray sync sleep time

---

artifactory/services/download.go
artifactory/services/upload.go
artifactory/services/utils/aqlquerybuilder.go
artifactory/services/utils/aqlquerybuilder_test.go
artifactory/services/utils/artifactoryutils.go

-----
Fix Downloading latest version using --build flag
https://github.com/jfrog/jfrog-cli/issues/1110
(When trying to download the artifacts from Arifactory using Jfrog CLI and specifying the --build option and it is expected to fetch the latest version but it is not fetching the latest #version.)

Fix download latest build number

---

config/configbuilder.go
utils/io/fileutils/files.go

Fix double slashes in download target path (v1)

---

artifactory/services/upload.go
http/httpclient/client.go

Add response body prints to retry warn messages

---

artifactory/services/fspatterns/utils.go
artifactory/services/upload.go
bintray/services/upload.go
config/configbuilder.go
utils/utils.go

V1: Archiving symlinks in upload command

---

artifactory/buildinfo/buildinfo.go

Add ExcludedArtifacts to build info

---

artifactory/buildinfo/buildinfo.go

V1: Add ExcludedArtifacts to build info

---

utils/io/fileutils/files.go

Preserve file's permissions when moving a file

---

utils/io/fileutils/files.go

Preserve file's permissions when moving a file (v1)

---

artifactory/services/upload.go

-----
Fails archiving symlinks with non-exists target.
Related v2 PR: https://github.com/jfrog/jfrog-client-go/pull/417

V1 Fix: Archiving broken symlink for upload command

---

README.md
artifactory/emptymanager.go
artifactory/manager.go
artifactory/services/federatedrepository.go
artifactory/services/federation.go
artifactory/services/localrepository.go
artifactory/services/remoterepository.go
artifactory/services/repositories.go
artifactory/services/repository.go
artifactory/services/virtualrepository.go
tests/artifactoryfederatedrepository_test.go
tests/artifactoryfederation_test.go
tests/artifactorylocalrepository_test.go
tests/artifactoryremoterepository_test.go
tests/artifactoryvirtualrepository_test.go
tests/jfrogclient_test.go
tests/utils.go

-----
Added all supported `federated repository` types, this is required before adding the necessary Terraform resources in https://github.com/jfrog/terraform-provider-artifactory, which is a much needed feature before we can switch to using `federated repositories`.

Add federated repositories

---

artifactory/services/buildinfo.go

New build link fix

---

README.md
access/auth/accessdetails.go
access/manager.go
access/services/project.go
appveyor.yml
artifactory/services/utils/artifactoryutils.go
artifactory/services/utils/searchutil.go
artifactory/services/utils/specutils.go
go.sum
tests/access_test.go
tests/accessproject_test.go
tests/jfrogclient_test.go
tests/utils.go
utils/errorutils/errorutils.go

V1: Add projects support

---

tests/artifactoryremoterepository_test.go

-----
To create/update a remote docker repository, it is required that 'artifacts stored locally ' will be set.

Fix docker tests

---

.github/workflows/tests.yml
tests/utils_test.go

Shorten repository name in tests

---

.github/workflows/tests.yml
tests/artifactoryusers_test.go
tests/utils_test.go

Bugfix - Incorrect repositories names in windows

---

xray/services/scan.go

Correcting Cvess score data types

---

.github/workflows/tests.yml
tests/xraypolicy_test.go

Fix Xray tests and stabilize pipelines tests

---

go.mod
go.sum
xray/services/scan.go
xray/services/scan_test.go

Remove scan type

---

artifactory/services/utils/artifactoryutils.go
artifactory/services/utils/parsebuildnamenumber_test.go

-----
Related PRs: 
* https://github.com/jfrog/jfrog-cli/pull/1310
* https://github.com/jfrog/jfrog-cli-core/pull/261

Add the option to set build name from the config file

---

xray/services/buildscan.go

Add missing build scan project query param

---

xray/services/scan.go

Return xray data url from build scan

---

tests/artifactorygroup_test.go
tests/artifactoryremoterepository_test.go
tests/artifactoryusers_test.go

Fix testAddUsersToGroup

---

artifactory/services/utils/searchutil.go

-----
Related PRs:
* https://github.com/jfrog/jfrog-cli-core/pull/293
* https://github.com/jfrog/jfrog-cli/pull/1364
* https://github.com/jfrog/build-info-go/pull/27

Remove repo from build-info path

---

artifactory/services/utils/tests/xray/consts.go
go.mod
xray/services/report.go

Fix Xray report CVSS type

---

README.md
artifactory/emptymanager.go
artifactory/manager.go
artifactory/services/repositories.go
tests/artifactorylocalrepository_test.go
tests/artifactoryremoterepository_test.go
tests/artifactoryvirtualrepository_test.go
tests/utils_test.go

Add new IsRepoExists API

---

.github/workflows/tests.yml
tests/artifactoryfederatedrepository_test.go
tests/artifactoryfederation_test.go
tests/artifactorylocalrepository_test.go
tests/artifactoryremoterepository_test.go
tests/artifactoryvirtualrepository_test.go
tests/utils_test.go

-----
All Artifactory and Repository tests will run on a local Artifactory.
Fixed the repositories tests.

Run tests on local Artifactory

---

utils/tests/utils.go

Improve SetEnvWithCallbackAndAssert func

---

utils/log/logger.go

Add log flags support

---

.github/workflows/tests.yml
README.md
tests/artifactory_test.go
tests/jfrogclient_test.go
tests/utils_test.go

Added missing test type to teardown.

Delete default test repo after repositories tests

---

artifactory/services/promote.go

-----
When running build promotion with failFast=false the command runs despite any errors that happen during the promotion.
Added a log to print the errors.

Build promotion failFast error logs (v1)

---

artifactory/services/utils/artifactoryutils.go

-----
Improved handling so it will be clear to the user why the command failed.
Following https://github.com/jfrog/jfrog-cli/issues/1432 and some similar questions.

Fix error handling on latest build fetch from artifactory

---

artifactory/services/utils/aqlquerybuilder.go

-----
Related PR: https://github.com/jfrog/build-info-go/pull/58

Move npm dependencies checksum calculation to build-info-go

---

utils/utils.go

Bugfix - missing close call in Go publish

---

artifactory/buildinfo/buildinfo.go
artifactory/services/utils/resultutils.go
artifactory/services/utils/searchutil.go
tests/utils.go

-----
Following https://github.com/jfrog/jfrog-cli-core/pull/342 changes.

V1 - Remove pointer from embedded checksum struct

---

xray/services/summary.go

Fix: "summary" typo

---

go.mod
go.sum

Update dependency versions 

---

auth/authutils_test.go
utils/regexputils_test.go
xray/services/scan.go

Modify XrayGraphScanParams for Frogbot

---

README.md
artifactory/services/utils/tests/xray/consts.go
artifactory/services/utils/tests/xray/server.go
tests/xraysummary_test.go
xray/manager.go
xray/services/summary.go

-----
Closes https://github.com/jfrog/jfrog-client-go/issues/528

Implement GetArtifactSummary

---

README.md
artifactory/services/users.go
tests/artifactoryusers_test.go

Add option to clear user's group

---

xray/services/scan.go

-----
Added References to Xray's Vulnerability struct.

Added field to Xray scan results

---

tests/utils_test.go

Use AccessToken instead of user & password

---

xray/services/scan.go

-----
Parse errors returned from Xray on graph scanning.
Parse JFrog research information returned from Xray on graph scanning.

Parse errors and new fields from Xray

---

tests/artifactorygroup_test.go
tests/artifactoryusers_test.go

Fix add_users test

---

utils/io/progress.go

Update ProgressMgr interface

---

.github/release.yml

Automatically generates release notes

---

utils/log/logger.go

Redirect log.Output if needed

---

utils/git.go
utils/git_test.go

-----
Move git execution functionality from test's utils.
Will be used in Froggbot commands.

Move git execute functionality

---

.github/workflows/analysis.yml
tests/distribution_test.go
xray/services/scan.go

Remove non-existing VulnerableComponents field and Fix Distribution test

---

go.mod
go.sum

-----
The change is identical to https://github.com/jfrog/jfrog-client-go/pull/565 which has already been reviewed and implemented for v2 of jfrog-client-go.

V1: Upgrade golang.org/x/crypto

---

README.md
artifactory/emptymanager.go
artifactory/manager.go
artifactory/services/export.go
tests/artifactoryexport_test.go

New Artifactory export service

---

utils/log/logger.go

Removed ability for the Logger to be nil and require a panic

---

.github/workflows/frogbot.yml

Add Frogbot

---

.github/workflows/frogbot-fix.yml
.github/workflows/frogbot-scan-pr.yml

Use Frogbot v2

---

README.md
artifactory/emptymanager.go
artifactory/manager.go
artifactory/services/system.go
tests/artifactorysystem_test.go
tests/jfrogclient_test.go
tests/utils_test.go
utils/io/httputils/pollingexecutor.go

-----
Add new methods for Artifactory on prem: 
* GetConfigDescriptor
* ActivateKeyEncryption
* DeactivateKeyEncryption

New methods in the system service

---

xray/services/buildscan.go

Adding support for rescan flag on xr bs

---

artifactory/services/download.go
artifactory/services/go/go_test.go
artifactory/services/go/goutils.go
artifactory/services/go/publish.go
artifactory/services/upload.go
artifactory/services/utils/resultutils.go
tests/artifactorydownload_test.go
tests/artifactoryupload_test.go
utils/log/logger.go
utils/utils.go

-----
Related to:
*  https://github.com/jfrog/jfrog-cli/pull/1564
* https://github.com/jfrog/jfrog-cli-core/pull/411

Rename isTerminalMode to isTerminal and move the RT URL to a dedicated variable in FileTransferDetails

---

README.md
artifactory/emptymanager.go
artifactory/manager.go
artifactory/services/movecopy.go
artifactory/services/props.go
artifactory/services/storage.go
artifactory/services/utils/properties.go
artifactory/services/utils/searchutil.go
artifactory/services/utils/storageutils.go
go.mod
go.sum
tests/artifactorystorage_test.go
tests/jfrogclient_test.go
tests/utils_test.go
utils/parenthesesutils.go

Add storage services

---

README.md
artifactory/services/utils/storageutils.go
tests/artifactorystorage_test.go

Improve storage info service

---

tests/artifactoryusers_test.go

-----
Fix the following error in the tests:
```
artifactoryusers_test.go:34: 
Error Trace:	/Users/runner/work/jfrog-client-go/jfrog-client-go/tests/artifactoryusers_test.go:34
Error:      	Should be true
Test:       	TestUsers/create
```

Fix users tests

---

artifactory/services/upload.go
artifactory/services/upload_test.go

-----
Fixing https://github.com/jfrog/jfrog-cli/issues/1595

Failure to calculate final results summary during upload

---

utils/git.go

-----
fixing https://github.com/jfrog/jfrog-cli/issues/1553

Fix git branch name slash issue

---

go.mod
xray/services/scan.go

Added 'Technology' field for vulnerability/violation structs

---

README.md
artifactory/services/groups.go
tests/artifactorygroup_test.go

feat(get-all-groups): Add Client API to get all groups from Artifactory

---

artifactory/services/download.go
http/httpclient/client.go

-----
This change is in relation to [this feature request](https://github.com/jfrog/jfrog-cli/issues/1636).

Add ability to ignore hash check failures when downloading

---

artifactory/services/download.go
http/httpclient/client.go

-----
After discussion, it was decided that `SkipChecksum` was a better name
for this flag.
Feature Request: https://github.com/jfrog/jfrog-cli/issues/1636

Rename IgnoreHashCheck to SkipChecksum

---

README.md
artifactory/emptymanager.go
artifactory/manager.go
artifactory/services/users.go
tests/artifactoryusers_test.go

Getting locked users and unlocking users in Artifactory

---

artifactory/emptymanager.go
artifactory/manager.go

- [*] This pull request is on the dev branch.
- [*] I used gofmt for formatting the code before submitting the pull request.
-----

Expose get all groups to service managers

---

.github/ISSUE_TEMPLATE/bug_report.md

Improve bugs reporting view to Github's new Issue Form UI

---

auth/authutils.go

-----
Following https://github.com/jfrog/jfrog-cli/issues/1693 and https://github.com/jfrog/jfrog-cli/issues/1616

Add hint for for Identity/Reference Tokens errors

---

go.mod
go.sum

-----
Upgrade the ssh-agent package following a bug found in windows and fixed on https://github.com/xanzy/ssh-agent/commit/0fa644ba07f41bbe341c7f3d59bd30443ff13002
Fixes issue https://github.com/jfrog/jfrog-cli/issues/1697

Update ssh-agent package version for windows bug

---

README.md
artifactory/services/federatedrepository.go
artifactory/services/localrepository.go
artifactory/services/remoterepository.go
artifactory/services/virtualrepository.go
tests/artifactoryfederatedrepository_test.go
tests/artifactorylocalrepository_test.go
tests/artifactoryremoterepository_test.go
tests/artifactoryvirtualrepository_test.go

feat: Add swift support for local remote virtual and federated repos

---

auth/authutils.go

Fix reference token error hint

---

utils/io/httputils/pollingexecutor.go
utils/utils.go
utils/utils_test.go

Fix converting local pattern to Regexp on windows 

---

appveyor.yml
artifactory/services/utils/tests/files.go
artifactory/services/utils/tests/xray/server.go
auth/cert/loader.go
auth/sshlogin.go
go.mod
go.sum
http/httpclient/client.go
http/httpclient/retryableconnection_test.go
tests/artifactorydockerpromote_test.go
tests/artifactorydownload_test.go
tests/distribution_test.go
tests/utils.go
utils/errorutils/errorutils.go
utils/git.go
utils/io/content/contentwriter_test.go
utils/io/fileutils/files.go
utils/io/fileutils/temp.go
utils/utils.go

Upgrade GO to 1.19

---

distribution/manager.go

New config accessor in DistributionServicesManager

---

go.mod
go.sum

Upgrade build-info-go to v1.8.4

---

utils/tests/utils.go

Signed-off-by: Michael Sverdlov <michaelsv@jfrog.com>
-----

Make tests run sequentially

---

access/manager.go
access/services/ping.go
artifactory/services/dockerpromote.go
artifactory/services/ping.go
artifactory/services/props.go
artifactory/services/storage.go
artifactory/services/utils/searchutil.go
distribution/services/create.go
distribution/services/deletelocal.go
distribution/services/deleteremote.go
distribution/services/distribute.go
distribution/services/getstatus.go
distribution/services/setsigningkey.go
distribution/services/sign.go
distribution/services/update.go
tests/accessping_test.go
tests/jfrogclient_test.go
tests/utils_test.go

New - JFrog Access ping service

---

utils/git.go

-----
Fixes jfrog/jfrog-cli#1531

Return git common dir to address worktree issues

---

artifactory/services/fspatterns/utils.go
artifactory/services/upload.go

Handle NPE while uploading dirs with no checksum

---

README.md
pipelines/manager.go
pipelines/services/sources.go
tests/pipelinesrun_test.go
tests/pipelinessources_test.go

Added source deletion check before creating source in pipeline run tests

---

artifactory/services/upload.go

-----
Fixes a race condition, where calls for removing a progress bar are made after it has already quitted.

Fix possible progress bar NPE on archive upload

---

.github/workflows/analysis.yml
.github/workflows/frogbot-fix.yml
.github/workflows/frogbot-scan-pr.yml
.github/workflows/tests.yml
go.mod

Upgrade go version in go.mod to 1.20

---

utils/utils.go

Promote version to 1.28.1

---

go.mod
go.sum
utils/errorutils/errorutils.go
xray/services/scan.go

Improve Xray failure log when scan graph fails on Xray side

---

utils/log/logger.go
xray/services/scan.go
xray/services/scan_test.go

Audit - Log the list of flattened dependencies in debug

---

go.mod
go.sum
utils/utils.go

Promoted version to 1.28.2

---

utils/io/fileutils/files.go

Missing clean in GetLocalPathAndFile

---

utils/io/fileutils/temp.go

Allow retrieving the temp dir base

---

go.mod
go.sum
utils/utils.go

Promoted version to 1.28.3

---

go.mod
go.sum
utils/utils.go

Promoted version to 1.28.5

---

.github/workflows/analysis.yml
.github/workflows/frogbot-scan-and-fix.yml
.github/workflows/tests.yml

Avoid running tests and static analysis on tags

---

utils/utils.go

Promoted version to 1.29.0

---

utils/utils.go

Merge to dev

---

http/httpclient/client.go

Unreleased bug progress bar value fix

---

http/httpclient/client.go

Improve GetRemoteFileDetails error response

---

README.md
access/manager.go
access/services/login.go
tests/accesslogin_test.go

-----
Will become available once Artifactory 7.63.1 is released to self-hosted

Add web login service

---

artifactory/services/delete.go
artifactory/services/download.go
artifactory/services/gitlfsclean.go
artifactory/services/movecopy.go
artifactory/services/upload.go
artifactory/services/utils/deleteutils.go
http/httpclient/client.go
utils/git.go
utils/io/content/contentreader.go
utils/io/fileutils/files.go
utils/io/fileutils/temp.go
utils/io/fileutils/zip.go

Fix wrongly errors return

---

http/httpclient/client.go

-----
following https://github.com/jfrog/jfrog-cli/issues/2064

Improve upload detailed error response

---

utils/utils.go

Align dev branch with master

---

utils/utils.go

Promoted version to 1.31.2

---

utils/utils.go

Promoted version to 1.31.6

---

xray/usage/reportusage.go
xray/usage/reportusage_test.go

-----
Xray fixes the bug that only admins can send usage reports. the fix will be available in Xray v3.83

Update min Xray usage version

---

artifactory/services/utils/artifactoryutils.go

Fix latest build not found handling

---

artifactory/services/utils/artifactoryutils.go

-----
Follow-up https://github.com/jfrog/jfrog-client-go/pull/835

Fix panic when build doesn't exist

---

utils/utils.go

Promoted version to 1.34.1

---

utils/git.go

-----
Restore errors that were deleted unintentionally in https://github.com/jfrog/jfrog-client-go/pull/795

Fix error handling in git utils

---

utils/utils.go

Promote version to v1.34.2

---

go.mod
utils/utils.go

Promote version to 1.34.3

---

utils/utils.go

Promoted version to 1.34.4

---

artifactory/services/remoterepository.go
artifactory/services/repository.go

Add cdnRedirect flag to local and remote repositories base params

---

utils/utils.go

Promoted version to 1.34.5

---

utils/utils.go

Promote version to 1.35.5

---

xray/services/scan.go

-----
remove check error and add comment

Fix after Changes to MSI

---

utils/utils.go
xray/services/scan.go

Promote version to '1.36.1'

---

lifecycle/services/create.go

Artifactory Release Lifecycle Management - Add include dependencies option to release bundle creation

---

utils/utils.go

Fix Master-Dev conflicts

---

go.mod
go.sum
utils/utils.go

Promote version to 1.37.0

---

go.mod
go.sum
utils/utils.go

Promote version to 1.37.1

---

go.mod
go.sum
lifecycle/manager.go

Artifactory Release Lifecycle Management - Avoid sending null path mapping

---

README.md
distribution/services/getstatus.go
lifecycle/lifecycle_test.go
lifecycle/manager.go
lifecycle/services/status.go

Artifactory Release Lifecycle Management - get lifecycle release bundle specification

---

go.mod
go.sum

-----
Include https://github.com/jfrog/gofrog/pull/54

Fix false positive ZipSlip when an archive starts with dot

---

artifactory/services/delete.go

-----
before:
will fix the following CLI issues:
https://github.com/jfrog/jfrog-cli/issues/682
https://github.com/jfrog/jfrog-cli/issues/1794

Mock dry run deletion success

---

README.md
distribution/services/distribute.go
lifecycle/lifecycle_test.go
lifecycle/manager.go
lifecycle/services/delete.go
lifecycle/services/distribute.go
lifecycle/services/promote.go
lifecycle/services/status.go
utils/distribution/distribute.go

Artifactory Release Lifecycle Management - Support release bundles deletion

---

xray/services/scan.go

XRAY-20331: Add CWE and CWE Details in Vulnerabilities model

---

README.md
artifactory/services/upload.go
artifactory/services/utils/multipartupload.go
artifactory/services/utils/multipartupload_test.go
artifactory/services/utils/storageutils.go
artifactory/services/utils/storageutils_test.go

Support providing chunk size in multi part upload

---

xray/services/utils/graph.go

Classifier property added to GraphNode struct

---

utils/utils.go

Promote version to v1.40.2

---

utils/utils.go

Promote version to 1.41.1

---

artifactory/services/fspatterns/utils.go

Fix symlink handling for upload with size limit

---

go.mod
go.sum
utils/utils.go

Promote version to 1.42.0

---

.github/workflows/analysis.yml
.github/workflows/cla.yml
.github/workflows/frogbot-scan-pull-request.yml
.github/workflows/frogbot-scan-repository.yml
.github/workflows/tests.yml

Unite all common GitHub action steps

---

.github/workflows/tests.yml

Remove JFrog Pipelines tests

---

go.mod
go.sum
utils/utils.go

Promoted version to 1.43.1

---

go.mod
go.sum
utils/utils.go

Release 1.43.2

---

utils/utils.go

Promote to 1.44.1

---

go.mod
go.sum
utils/utils.go

Release 1.46.0

---

utils/utils.go

Promote version to 1.46.1

---

utils/log/logger_test.go

Remove log tests

---

utils/utils.go

Ignore minimum version check when running against Xray DEV version

---

go.sum
utils/utils.go

Promote version to v1.48.0

---

xray/services/xsc/xsc.go
xsc/manager.go
xsc/services/utils/utils.go
xsc/services/utils/utils_test.go

-----
Changing the min version of XSC in Xray

Change XSC in Xray min version to 3.107.13

---

xray/services/scan.go

-----
Don't use XSC services if MultiScanId does not exist.

No MSI No XSC

---

artifactory/usage/call_home.go

* Remove the minimum Artifactory version validation before sending the Call Home requests, since the validation moves to the caller of the API. This is done to avoid duplicate "Get Artifactory Version" requests.
* Rename the API functions, to force the callers to adapt to this change.

Internal - Remove the Call Home version validation

---

utils/utils.go

Bump version to v1.49.0

---

utils/utils.go

Promote version to 1.49.1

---

tests/xrayenrich_test.go
xray/manager.go
xray/services/enrich.go

-----
Description:
Send file name to platform which is being enriched on jf sbom-enrich command

Send filename to xray on sbom-enrich api

---

go.mod
go.sum
utils/utils.go

Promote version 1.51.0

---

http/httpclient/client.go

Fix spelling

---

utils/utils.go

Update dependencies 1.51.1

---

xsc/services/watch.go

Improving misleading log about Watches fetch from platform resources

---

utils/utils.go

Promote Version to `v1.52.0`

---

go.mod
go.sum
utils/utils.go

bump version to v`1.53.0`

---

utils/utils.go

Promote version to `1.53.1`

---

go.mod
go.sum
utils/utils.go

Promote version to `v1.54.0`

---

access/services/accesstoken.go
tests/accesstokens_test.go

-----
Add a context object inside the exchange request:
```go
type VcsCommit struct {
VcsUrl   string `json:"vcs_url,omitempty"`
Branch   string `json:"branch,omitempty"`
Revision string `json:"revision,omitempty"`
}
type Context struct {
VcsCommit *VcsCommit `json:"vcs_commit,omitempty"`
}
```

Add OIDC context struct

---

.github/workflows/tests.yml
artifactory/services/promote.go
artifactory/services/utils/tests/catalog/server.go
catalog/auth/catalogdetails.go
catalog/manager.go
catalog/services/enricher.go
catalog/services/version.go
tests/catalog_test.go
tests/utils_test.go
utils/log/logger.go

-----
Add **Catalog** services
* `Version` - returns `catalog` version
* `Enrich` - enrich a given CDX file with catalog information

Add catalog services

---

artifactory/emptymanager.go
artifactory/services/permissiontarget.go

-----
Thank you for merging PR #1141.
I'm identified an issue in the implementation, so we would appreciate it if you could also merge this PR.
Apologies for the inconvenience, and thank you for your understanding.

fix: GetPermissionTargets, PermissionTargetParams

---

utils/utils.go

Promoted version to 1.54.6

---

access/services/project.go
jpd/jpd.go

-----
What: Replace log field name with write.

Addressed comments
