- artifactory/auth/cert/loader.go
- artifactory/services/download.go
- artifactory/services/download_test.go
- artifactory/services/fspatterns/utils.go
- artifactory/services/gitlfsclean_test.go
- artifactory/services/upload.go
- artifactory/services/utils/artifactoryutils.go
- bintray/services/download.go
- bintray/services/upload.go
- httpclient/client.go
- utils/io/fileutils/files.go
- utils/io/fileutils/listfiles.go
Fixed jfrog-cli-go #229.
Added the ability to upload broken symlinks with --symlinks=true.
Fixed an issue where when --symlinks=false, the symlink target would be uploaded given the symlink name instead of the target name.
> Upload broken symlinks fixed

- artifactory/services/fspatterns/utils.go
- artifactory/services/upload.go
- utils/io/fileutils/files.go
Fixed jfrog-cli-go #229.
Added the ability to upload broken symlinks with --symlinks=true.
Fixed an issue where when --symlinks=false, the symlink target would be uploaded given the symlink name instead of the target name.
> Upload broken symlinks

- artifactory/services/download.go
- artifactory/services/upload.go
- artifactory/services/utils/fileinfoutils.go
- artifactory/services/utils/utils.go
Fixed the following issues:
- Artifact's local path was constructed incorrectly.
- The artifact's file name for build info was taken from local path instead of artifactory path.
> Build info wrong artifact name - bug fix

- utils/log/logger.go
Logger will no longer take the log-level from JFROG_CLI_LOG_LEVEL.
Instead, it will receive its log-level value from the log creator.
> Change the way Logger is created

- utils/io/fileutils/files.go
Following the input https://github.com/jfrog/jfrog-cli-go/issues/382, this PR enhances the *GetHomeDir* function, so that it also uses the **USERPROFILE** environment variables (set on Windows machines) to find the user home directory.
> Support the USERPROFILE env var as the default home dir.

- httpclient/client.go
This PR fixes the following issue in JFrog CLI (which uses the jfrog-client-go library).
```
$ jfrog rt dl generic-local/te.tar.gz ./ --explode
[Info] Searching items to download...
[Info] [Thread 2] Downloading generic-local/te.tar.gz
[Info] [Thread 2] Extracting archive: te.tar.gz to .
[Warn] [Thread 2] Attempt 0 - Failure occurred while downloading http://localhost:8081/artifactory/generic-local/te.tar.gz - test/: illegal file path
[Info] [Thread 2] Extracting archive: te.tar.gz to .
[Warn] [Thread 2] Attempt 1 - Failure occurred while downloading http://localhost:8081/artifactory/generic-local/te.tar.gz - test/: illegal file path
[Info] [Thread 2] Extracting archive: te.tar.gz to .
[Warn] [Thread 2] Attempt 2 - Failure occurred while downloading …
```
> "jfrog rt dl generic-local/te.tar.gz ./ --explode" fails.

- artifactory/httpclient/httpclient.go
Some API endpoints want form encoded data in a POST request.
Make it easier to implement these services by provided a PostForm
equivalent in the httpclient.
Analogous to https://golang.org/pkg/net/http/#Client.PostForm
> artifactory httpclient: Add SendPostForm

- artifactory/services/delete.go
- artifactory/services/download.go
- artifactory/services/movecopy.go
- artifactory/services/search.go
- artifactory/services/utils/searchutil.go
- artifactory/services/utils/specutils.go
Skip AQL search of all artifacts (Pattern == '*' or Pattern == '') when build name and number exist.
> Optimize search by build without pattern

- httpclient/client.go
When providing a relative path as target to download explode, the following error was thrown:
```
jfrog rt dl generic-local/a.zip ./ --explode
[Info] [Thread 2] Extracting archive: a.zip to .
[Warn] [Thread 2] Attempt 3 - Failure occurred while downloading http://127.0.0.1:8081/artifactory/generic-local/a.zip - tmp/ziptry/: illegal file path
[Error] [Thread 2]  Received an error: tmp/ziptry/: illegal file path
[Error] tmp/ziptry/: illegal file path
{
"status": "failure",
"totals": {
"success": 0,
"failure": 1
}
}
```
> Fix relative path in download explode

- artifactory/services/fspatterns/utils.go
- artifactory/services/utils/aqlquerybuilder.go
- artifactory/services/utils/specutils.go
- tests/artifactorydownload_test.go
Allow excluding repositories in all AQL based operations:
1. Add new `--exclusions` flag, and `exclusions` field in fileSpec.
2. Deprecate `--exclude-patterns` flag and `excludePatterns` field in fileSpec.
> Allow excluding repositories in all AQL based operations

- README.md
- artifactory/services/security.go
- artifactory/services/security_test.go
see  #127 
Solution slightly changes behaviour for defaults. Consider following:
```
securityService := NewSecurityService(client)
securityService.CreateToken(CreateTokenParams{Username: "test"})
```
Without this MR no `expires_in` is send to the server, with this MR expires_in=0 is sent and the issued token never expires. 
If the API is used with `NewCreateTokenParams` function there is no difference.
```
securityService := NewSecurityService(client)
params := NewCreateTokenParams()
params.Username = "test"
securityService.CreateToken(params)
```
Also negative values are no more sent to the server and so the server default is used.
Maybe thats not the best solution. I am open for ideas!
> fixed expires_in=0 (never expires)

- artifactory/buildinfo/buildinfo.go
- artifactory/buildinfo/config.go
- artifactory/buildinfo/config_test.go
This PR addresses Issue #169 by adding the Filter implementation of the CLI in this client library, making it usable by all downstream consumers.
Test case output:
```
$ go test -cover -v github.com/jfrog/jfrog-client-go/artifactory/buildinfo
=== RUN   TestInclude
=== RUN   TestInclude/empty_input
=== RUN   TestInclude/input_with_no_pattern
=== RUN   TestInclude/input_with_pattern
=== RUN   TestInclude/input_with_bad_pattern
=== RUN   TestInclude/input_with_prefix
--- PASS: TestInclude (0.00s)
--- PASS: TestInclude/empty_input (0.00s)
--- PASS: TestInclude/input_with_no_pattern (0.00s)
--- PASS: TestInclude/input_with_pattern (0.00s)
--- PASS: TestInclude/input_with_bad_pattern (0.00s)
--- PASS: TestInclude/input_with_prefix (0.00s)
=== RUN   TestExclude
=== RUN   TestExclude/empty_input …
```
> implement buildinfo environment filters

- artifactory/buildinfo/config.go
- artifactory/buildinfo/config_test.go
Following the merge of https://github.com/jfrog/jfrog-client-go/pull/170 which moved the env include and env exclude from jfrog-cli to jfrog-client-go, the code which was moved should also be deleted from jfrog-cli.
This pull request improves the API added by https://github.com/jfrog/jfrog-client-go/pull/170, to make it easier for jfrog-cli to use it, It removed the prefix argument, and replaces it with a const.
> Add BuildInfoEnvPrefix const

- distribution/services/utils/distributionutils.go
Release bundle create/update - When spec type is AQL, we ignore the AQL.
Precondition for: https://github.com/jfrog/jfrog-cli/pull/812
Resolves: https://github.com/jfrog/jfrog-cli/issues/809
> Bugfix - AQL is not supported in rbc/rbu

- utils/io/fileutils/temp.go
This PR fixes the following issue.
The ```CleanOldDirs()``` function an error, if ```tempDirBase``` includes directories which are not empty. This function is used by JFrog CLI after each execution. This issue can cause the following error:
```
$ jfrog -v
jfrog version 1.39.5
[Warn] remove /var/folders/cq/j4684j7n4bb_nlss5dy06mnr0000gn/T/jfrog.cli.temp.-1602145932-459087986: directory not empty
```
And here's the stack-trace:
```
$ export JFROG_CLI_ERROR_HANDLING=panic
$ jfrog -v
jfrog version 1.39.5
panic: remove /var/folders/cq/j4684j7n4bb_nlss5dy06mnr0000gn/T/jfrog.cli.temp.-1602145932-459087986: directory not empty
goroutine 1 [running]:
github.com/jfrog/jfrog-cli-core/utils/coreutils.PanicOnError(0x1b230e0, 0xc0001e06f0, 0x1b230e0, 0xc0001e06f0) …
```
> Bug fix - CleanOldDirs() does not delete dirs

- artifactory/emptymanager.go
The interface ArtifactoryServicesManager contains the private method
initDownloadService.  This means that gomock for example cannot be used
to generate a set of mocks for this interface which can then be used in
unit-testing.  In this change we simply remove initDownloadService from
ArtifactoryServicesManager, which means that it is now only defined and
used by ArtifactoryServicesManagerImp.
> Remove initDownloadService from ArtifactoryServicesManager

- README.md
- artifactory/httpclient/rtClientBuilder.go
- artifactory/manager.go
- config/config.go
- config/configbuilder.go
- distribution/manager.go
- httpclient/client.go
- httpclient/clientBuilder.go
- tests/artifactoryctx_test.go
-----
This add a context to the managers so they can execute http requests using a provided context. It probably fixes #192
> add context to managers

- utils/io/fileutils/files.go
> Fix fileutils MoveDir() path creation to support windows paths

- artifactory/buildinfo/buildinfo.go
> Fix time format used in build info

- artifactory/services/download.go
- httpclient/client.go
- utils/archiveutils.go
-----
Download & explode fails to unzip the archive file if it missing the extension on the filename. A simple solution is to override the name with its origin in Artifactory as it gets deleted anyway after we finish to extract successfully.
Related PR:
* https://github.com/jfrog/jfrog-cli/pull/932
> Bugfix- explode fail after overriding the archive filename

- utils/io/fileutils/files.go
-----
This PR fixes an issue with the ```MoveFile``` function, which the ```jfrog-cli``` tests revieled.
```
Error] [Thread 2]  Received an error: remove C:\Users\appveyor\AppData\Local\Temp\1\jfrog.cli.temp.-1608298394-408535009\randFile: The process cannot access the file because it is being used by another process.
[Error] remove C:\Users\appveyor\AppData\Local\Temp\1\jfrog.cli.temp.-1608298394-408535009\randFile: The process cannot access the file because it is being used by another process.
{
"status": "failure",
"totals": {
"success": 0,
"failure": 1
}
}
artifactory_test.go:739: 
Error Trace:	artifactory_test.go:739
Error:      	Received unexpected error:
Download finished with errors, please review the logs.
Test:       	TestArtifactoryDownloadAndExplode
```
Notice above that the …
> Fix MoveFile

- utils/git.go
- utils/regexputils.go
- utils/regexputils_test.go
-----
When the VCS URL contains a URL with credentials, instead of masking it with '***', remove the credentials. This way, the URL will be clickable.
For example:
Before the change:
`https://***:***@github.com/jfrog/jfrog-client-go`
After the change:
`https://github.com/jfrog/jfrog-client-go`
> Improve vcs url algorithm

- README.md
- artifactory/services/dockerpromote.go
- artifactory/services/promote.go
- artifactory/services/upload.go
- artifactory/services/utils/properties.go
- artifactory/services/utils/properties_test.go
- artifactory/services/utils/specutils.go
- distribution/services/utils/distributionutils.go
- distribution/services/utils/distributionutils_test.go
- distribution/services/utils/releasebundlebody.go
- tests/artifactoryupload_test.go
- tests/distribution_test.go
- utils/utils.go
-----
Precondition for: https://github.com/jfrog/jfrog-cli/pull/959, https://github.com/jfrog/jfrog-cli-core/pull/60
Allow adding properties to a created/updated release bundle.
See added_props in https://www.jfrog.com/confluence/display/JFROG/Distribution+REST+API#DistributionRESTAPI-CreateReleaseBundleVersion.
> Allow adding properties to release bundles

- README.md
- distribution/services/utils/distributionutils.go
- distribution/services/utils/distributionutils_test.go
- distribution/services/utils/releasebundlebody.go
- tests/distribution_test.go
- utils/utils.go
-----
Add support for Distribution path mapping.
File spec schema:
```json
{
"files": [
{
"pattern": "[Mandatory] Wildcard pattern match files in the source artifactory",
"target": "[Optinal] Path in the edge node"
}
]
}
```
The support is builtin in the file spec. When Target is provided, then the path mapping is activated. Artifacts matched in the Pattern will be mapped to the Target after distribution.
To complete the picture, placeholders will be used. The pattern can include capture groups surrounded by parenthesis and the target can include target groups surrounded by curly brackets.
Comparing to the REST API of the [CreateReleaseBundle](https://www.jfrog.com/confluence/display/JFROG/Distribution+REST+API#DistributionRESTAPI-CreateReleaseBundleVersion), there are 2 differences:
1. …
> Support path mapping in distibution commands

- README.md
- appveyor.yml
- tests/jfrogclient_test.go
- tests/utils.go
- tests/xraybinmgr_test.go
- tests/xraypolicy_test.go
- tests/xraywatch_test.go
- xray/manager.go
- xray/services/binMgr.go
- xray/services/policy.go
- xray/services/utils/policybody.go
- xray/services/watch.go
-----
Add JFrog Xray policy API support.
See usage here:
https://github.com/yahavi/jfrog-client-go/tree/xray-policy#creating-a-security-xray-policy
> Support Xray policy and build indexing APIs

- README.md
- artifactory/emptymanager.go
- artifactory/manager.go
- artifactory/services/buildinfo.go
- artifactory/services/discardBuilds.go
- artifactory/services/promote.go
- artifactory/services/utils/artifactoryutils.go
- artifactory/services/xrayscan.go
- tests/utils.go
-----
This PR enhances the client, so that it can support the new "projects" functionality introduced in Artifactory.
1. When publishing build-info, the project key can be optionally provided. If provided, the build-info is published to the project's build-info repository, named my-project-key-build-info. If not provided, the build-info is published (by default) to a repository named artifactory-build-info.
2. The project key is also optionally provided when fetching a published build-info. Same default as in #1.
3. Same project key option is also available when scanning a build.
> Support for Artifactory Projects

- artifactory/services/buildinfo.go
- artifactory/services/promote.go
- artifactory/services/utils/artifactoryutils.go
-----
This PR fixes the following issue that jfrog-cli's tests detected.
```
=== RUN   TestBuildPromote
[Info] Creating spec file at: /Users/eyalb/dev/jfrog-cli/tmp/upload_split_spec_a.json
[Info] [Command] jfrog rt upload --spec=/Users/eyalb/dev/jfrog-cli/tmp/upload_split_spec_a.json --build-name=cli-tests-rt-build1-1612861733 --build-number=10
[Info] [Thread 1] Uploading artifact: testdata/a/a1.in
[Info] [Thread 0] Uploading artifact: testdata/a/a2.in
[Info] [Thread 2] Uploading artifact: testdata/a/a3.in
{
"status": "success",
"totals": {
"success": 3,
"failure": 0
}
}
[Info] [Command] jfrog rt build-publish cli-tests-rt-build1-1612861733 10
[Info] Deploying build info...
[Info] Build info successfully deployed. Browse it in Artifactory under …
```
> Unreleased bug - build promotion fails, following the added support for Projects 

- artifactory/services/upload.go
Because uploadParams.BuildProps is global and props addition is being done
for each file, it make no sense to accumulate those props.
-----
> Remove redundant VCS props accumulation

- auth/sshlogin.go
-----
In the new OpenSSH format of the private SSH keys, the private keys do not contain the `Proc-Type: ENCRYPTED` header 
(See https://security.stackexchange.com/a/129729). Therefore, we have to find out whether the key is encrypted using another method.
To resolve this issue, I used [ParsePrivateKey](https://pkg.go.dev/golang.org/x/crypto/ssh#ParsePrivateKey) of Go builtin ssh package.
> Fix IsEncrypted for new Openssl format

- artifactory/services/buildinfo.go
- artifactory/services/utils/aqlquerybuilder.go
- artifactory/services/utils/aqlquerybuilder_test.go
- artifactory/services/utils/artifactoryutils.go
- artifactory/services/utils/artifactoryutils_test.go
- artifactory/services/utils/parsebuildnamenumber_test.go
- artifactory/services/utils/searchutil.go
-----
Integration tests on CLI: https://github.com/jfrog/jfrog-cli/pull/990
Support operations in transitive builds in all AQL-based commands: Search, Download, Delete, Move, Copy, and GitLfsClean.
Build A is considered transitive of build B if A is a module of B or another transitive build of B:
```json
{
"name": "B",
"modules": [{
"id": "A",
"type": "Build"
}]
}
```
> Support commands on aggregated builds

- artifactory/services/discardBuilds.go
- artifactory/services/promote.go
- artifactory/services/utils/artifactoryutils.go
- artifactory/services/xrayscan.go
-----
This PR replaces the usage of the "buildRepo" query param with "project", to be compliant with Artifactory's REST APIs requirements.
> Replace "buildRepo" with "project" on build APIs

- artifactory/emptymanager.go
- artifactory/manager.go
-----
README.md mentions that the `RegenerateAPIKey` function can be invoked using an instance of `manager`. 
```
apiKey, err := rtManager.RegenerateAPIKey()
```
This isn't true. This PR corrects this by implementing RegenerateAPIKey function in manager.go
> Add Regenerate API to manager

- tests/artifactorylocalrepository_test.go
-----
Download redirect is an Entplus feature:
> Download redirect is configured for repository 'jf-client-go-test-1617882021' but is only available on Enterprise Plus or Edge licensed Artifactory instances.
Remove it from Artifactory local tests to allow running tests on Artifactory pro.
> Allow running tests on Artifactory pro

- artifactory/services/permissiontarget.go
- tests/artifactorypermissiontarget_test.go
-----
Use `DELETE api/v2/security/permissions/<permissionTargetName>` 
instead of `DELETE api/security/permissions/<permissionTargetName>`
In some cases, the permission target is not deleted. To reproduce, run TestPermissionTarget.
Verified on:
* Artifactory 7.17.5 on artifactory-pro Docker image
* Artifactory 7.17.4 on Artifactory SaaS
> Use API v2 in delete permission target

- artifactory/services/utils/searchutil.go
-----
This PR fixes one of the issues reported at https://github.com/jfrog/artifactory-azure-devops-extension/issues/235.
The following command fails with a panic, if the filtered build does not exist - 
```
jfrog rt dl "*" "/home/vsts/work/r1/a/x/" --build="gradle-cli/1" --flat --fail-no-op
```
> Download fails with panic, if filtered build does not exist

- artifactory/services/promote.go
-----
FailFast needs to be always printed in the response since it defaults to true
> remove omitempty since default is true

- artifactory/services/download.go
- artifactory/services/movecopy.go
- artifactory/services/upload.go
- utils/io/fileutils/files.go
- utils/parenthesesutils.go
- utils/utils.go
- utils/utils_test.go
-----
Placeholders define the target path of each file for upload/download/move/copy commands. As `--flat` makes sense while using wildcard patter, there is no concrete meaning for using it with placeholders, resulting in unintuitive results.
For example, `mypath/{1}/{2}/{3}/{1}' as a target path, ` --flat` has no meaning since we create the structure for each file, As a result, the question if to use ` --flat` makes no sense here.
Resolves: https://github.com/jfrog/jfrog-cli/issues/883
Related PR: https://github.com/jfrog/jfrog-cli/pull/1131
> Placeholders logic ignores '--flat'

- utils/io/fileutils/files.go
> Fix double slashes in download target path

- auth/sshlogin.go
- go.mod
- go.sum
-----
* When SSH passphrase doesn't exist, `ssh.ParsePrivateKey` should be used instead of `ssh.ParsePrivateKeyWithPassphrase`.
* Upgrade crypto to the latest.
* Information about SSH communication should be under debug log level. Errors should be under Error log level.
> Allow SSH without passphrase

- artifactory/services/buildinfo.go
-----
Fixes https://github.com/jfrog/jfrog-cli/issues/158
> Encode build name and number when outputs build url

- artifactory/services/buildinfo.go
> V1: Encode build name and number when outputs build url

- artifactory/services/download.go
- artifactory/services/upload.go
- artifactory/services/utils/aqlquerybuilder.go
- artifactory/services/utils/aqlquerybuilder_test.go
- artifactory/services/utils/artifactoryutils.go
-----
Fix Downloading latest version using --build flag for v1
jfrog/jfrog-cli#1110
(When trying to download the artifacts from Arifactory using Jfrog CLI and specifying the --build option and it is expected to fetch the latest version but it is not fetching the latest #version.)
> Fix download latest build number for v1

- artifactory/services/upload.go
- http/httpclient/client.go
The new retries mechanism didn't worked due to reused of the http client
request struct.
In addition, a fail request message is now includes also the response body. 
-----
> V1: Bugfix - Retries Send Mechanism

- utils/utils.go
-----
Relevant deployment repository will be written by the buildinfo project to the diplyableArtifacts file starting from version 2.24.12 of build-info-extractor-gradle.
In case of a gradle project with a configuration of 'usePlugin=true' it's possible that an old build-info-extractor-gradle version is being used.
In this case, deployment repository will be read from the local project configuration file.
> Fix: Get deploy target repository while using old gradle plugins versions.

- artifactory/services/fspatterns/utils.go
- artifactory/services/upload.go
- utils/utils.go
-----
* Remove restriction about using --archive and --symlinks together.
* The combination of --archive, --symlinks and --explode together is still forbidden. 
When uploading a symlink to Artifactory, the symlink is represented in Artifactory as 0 size file with properties 
describing the symlink. This symlink representation is not yet supported by Artifactory when exploding symlinks from a zip.
> Archiving symlinks in upload command

- utils/utils.go
-----
Relevant deployment repository will be written by the buildinfo project to the diplyableArtifacts file starting from version 2.24.12 of build-info-extractor-gradle.
In case of a gradle project with a configuration of 'usePlugin=true' it's possible that an old build-info-extractor-gradle version is being used.
In this case, deployment repository will be read from the local project configuration file.
> Fix: Get deploy target repository while using old gradle plugins version

- artifactory/services/upload.go
-----
Fails archiving symlinks with non-exists target.
> Fix: Archiving broken symlink for upload command

- artifactory/services/upload.go
-----
Uploading a folder as a zip file with --include-dirs will exclude any empty directories in the folder.
> Fix: Upload with archive and include-dirs leaves out empty directories

- artifactory/services/upload.go
-----
Uploading a folder as a zip file with --include-dirs will exclude any empty directories in the folder.
Reviewed in PR: https://github.com/jfrog/jfrog-client-go/pull/415
> V1 Fix: Upload with archive and include-dirs leaves out empty directories

- README.md
- artifactory/manager.go
- auth/servicedetails.go
- config/config.go
- config/configbuilder.go
- http/httpclient/clientBuilder.go
- http/jfroghttpclient/clientbuilder.go
- tests/artifactorycustomhttpclient_test.go
-----
fixes #289 
This functionality can be used as follows:
```go
httpProxy := "http://localhost:54321"
rtDetails := auth.NewArtifactoryDetails()
rtDetails.SetUrl(artifactoryUrl.String())
if httpProxy != "" {
proxyUrl, err := url.Parse(httpProxy)
if err != nil {
return err
}
rtDetails.SetHttpClient(&http.Client{Transport: &http.Transport{Proxy: http.ProxyURL(proxyUrl)}})
}
rtDetails.SetUser("username")
rtDetails.SetPassword("password")
serviceConfig, err := config.NewConfigBuilder().
SetServiceDetails(rtDetails).
SetDryRun(false).
Build()
```
> Build Artifactory client with custom http.client.

- artifactory/services/federatedrepository.go
- artifactory/services/localrepository.go
- artifactory/services/repository.go
- artifactory/services/virtualrepository.go
I suggest to add those fields according to https://www.jfrog.com/confluence/display/JFROG/Repository+Configuration+JSON
Signed-off-by: francois  samin <francois.samin@corp.ovh.com>
-----
> Add KeyPairRef fields on local, federated and virtual repositories

- artifactory/services/utils/properties.go
- artifactory/services/utils/properties_test.go
-----
Properties value can now contain characters '=' and ';' .
In case of ';' character in the value - user should use a backslash prefix and write '\;' .
> Bugfix:  Upload with target-prop's value contain special characters

- artifactory/services/repository.go
-----
Repo key might change during the template creation to include project key. Printing the final key is convenient.
> Print repo name on creation

- utils/utils.go
> CreateFileTransferDetails - prevent double slash in target path

- utils/io/fileutils/archive.go
- utils/io/fileutils/archive_test.go
-----
To prevent absolute target paths outside of an extraction directory, we should use `filepath` instead of `path`.
This issue appeared after creating `TestUploadWithArchiveAndSymlinkZipSlip` in https://github.com/jfrog/jfrog-cli/pull/1269/files#diff-90b1ac3745fa656b3bbf876ff9778354050d926be2c38f2909ac328ef9542c1bR2017 and running it on Windows.
> Sanitize windows paths better on unarchive

- artifactory/services/utils/aqlquerybuilder.go
-----
When using npm install the command is searching for dependencies data in the repository.
Sometimes the dependency "npm.version" is prefixed with "v" and the AQL command fails to provide the dependency data.
With this fix, we will always check for both syntaxes(with/without "v" prefix)
Following [Issue 1138](https://github.com/jfrog/jfrog-cli/issues/1138)
> Fix npm install dependency version with "v" prefix

- http/httpclient/client.go
-----
httpClient printed duplicated log when running REST commands.
`Sending HTTP %s request to: ___ ` x2
> fix httpClient duplicate log

- .github/workflows/tests.yml
- go.mod
- go.sum
- tests/utils_test.go
-----
GitHub-Actions run in parallel. As a result, two different tests may get the same timestamp in the repository name.
We add an extra unique number (UUID) to the repositories creation flow.
> Add uuid to repository name

- .github/workflows/tests.yml
- README.md
- go.mod
- go.sum
- tests/accessproject_test.go
- tests/artifactorydownload_test.go
- tests/artifactorygroup_test.go
- tests/artifactorypermissiontarget_test.go
- tests/artifactoryreplication_test.go
- tests/artifactoryupload_test.go
- tests/artifactoryusers_test.go
- tests/artifactoryvirtualrepository_test.go
- tests/distribution_test.go
- tests/pipelinesintegrations_test.go
- tests/utils_test.go
- tests/xraybinmgr_test.go
- tests/xraypolicy_test.go
- tests/xraywatch_test.go
-----
Using the timestamp as a unique repository name is not 100% bullet-prove as two parallel tests in GitHub-Actions could get the same timestamp. 
In addition to the time stamp, there will be for each test its running os & test type (e.g. for Artifactory test in mac machine, the repository will be named, client-tests-ar-m-1637049275)
> Replace timestamp with run_number for the repository name

- .github/workflows/tests.yml
-----
Same as :
https://github.com/jfrog/jfrog-cli/pull/1299
> Cancle old runners in PR content

- utils/utils.go
- utils/utils_test.go
-----
Fix converting two asterisks to regex.
> Fix: Ant pattern to regex converting

- utils/io/httputils/pollingexecutor.go
- utils/io/progress.go
- xray/services/scan.go
-----
This pull request adds the new PollingExecutor that introduces HTTP polling implementation.
As well as minor progress API changes needed for the new free-tier setup command.
> Add support for new free-tier setup command

- utils/utils.go
- utils/utils_test.go
-----
Fix converting two asterisks to regex.
> Fix v1: Ant pattern to regex converting

- artifactory/services/utils/aqlquerybuilder.go
- artifactory/services/utils/repopathfile.go
- artifactory/services/utils/repopathfile_test.go
- go.mod
-----
Exclusion patterns must start with a repository name or an asterisk.
Fixed a bug when an exclusion started with an asterisk in transitive search, which caused an error to be returned from Artifactory.
> Fix exclusions in transitive search (v1)

- xray/services/scan.go
-----
Increase build-scan and scan-graph default timeout to 45 minutes.
> Increase scan timeout to 45 minutes

- artifactory/services/utils/searchutil.go
-----
Readers' sort fails for missing ending slash in folders' key.
Before the fix:
"cli-rt2-1641454539/()"                     "cli-rt2-1641454539/("
"cli-rt2-1641454539/("          ->.       "cli-rt2-1641454539/()" 
"cli-rt2-1641454539/(/b(.in".             "cli-rt2-1641454539/(/b(.in"
After:
"cli-rt2-1641454539/()"                     "cli-rt2-1641454539/(/"
"cli-rt2-1641454539/(/"          ->.       "cli-rt2-1641454539/(/b(.in" 
"cli-rt2-1641454539/(/b(.in".             "cli-rt2-1641454539/()"
> Bugfix - append ending slash to sort key

- distribution/services/distribute.go
- utils/io/httputils/pollingexecutor.go
- utils/retryexecutor.go
Unify polling and retry executor logic.
From now on, the polling executor will use the retry implemented utility instead
of its separate implementation.
-----
> Polling executor refactor

- artifactory/services/buildinfo.go
- auth/cert/sslutils_default.go
- auth/cert/sslutils_windows.go
-----
This is part of a fix for V1, which has already been implemented for V2 a few months ago.
This PR removes the "Build info successfully published" log message. It is a duplicate of https://github.com/jfrog/jfrog-client-go/pull/419 which has been merged to v2 a few months ago. This was done, in order to support a fix for an issue, whereby the build-info link displayed in the log, was incorrect, when the build is published as part of a project. 
As part of the fix, the fixed link is built and displayed by jfrog-cli-core, and is therefore removed from jfrog-client-go in this PR.
A PR for jfrog-cli-core will be soon created.
> V1 - Remove 'build-info published' log message

- artifactory/services/utils/aqlquerybuilder.go
- artifactory/services/utils/repopathfile.go
- artifactory/services/utils/repopathfile_test.go
-----
Fixed some issues regarding limitations in transitive search: repository name cannot contain wildcards; limit() comes after transitive() in the complete AQL query.
> Follow transitive search limitations

- .github/workflows/tests.yml
Pipelines tests are remote only and does not the involve the filesystem, hence running them on more than one os is redundant.
> Run pipelines tests on one os only

- artifactory/services/promote.go
-----
When running build promotion with failFast=false the command runs despite any errors that happen during the promotion.
Added a log to print the errors.
> Build promotion failFast error logs

- artifactory/services/utils/artifactoryutils.go
-----
The log level is incorrect as it shows the following messages for the first time while using `jf project init`:
> Change log level for missing LATEST build in Artifactory

- artifactory/services/createreplication.go
- artifactory/services/getreplication.go
- artifactory/services/updatereplication.go
- artifactory/services/utils/replication.go
-----
I have a use case where I am trying to configure Artifactory replications through Terraform and need to be able to set a proxy for the replication.  Couple things to note about the current changes:
1. The GET JSON response for getting a replication has changed between Artifactory 6.x and 7.x such that this change would only work for 7.x.  See https://github.com/atlassian/go-artifactory/pull/33, an old PR,  for the change for Artifactory 6.x.
2. I wanted to added a test for this, but unfortunately was not able to figure out how to dynamically create a proxy via a REST API (couldn't find anything on https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API).  If you can help point me in the right direction wrt this, I would love to add a test for configuring proxy.  I have …
> Fixes #523 Add capability to specify proxy for repository replications

- artifactory/services/utils/replication.go
- tests/artifactoryreplication_test.go
-----
Allow using the IncludePathPrefixPattern parameter in replication.
> Support IncludePathPrefixPattern param in replication

- xray/services/scan.go
Extend the existing violation schema to allow populating operational risk data.
-----
> Add Operational Risk fields to Xray Scan Violation schema

- xray/services/summary.go
-----
Fixes spelling of summary (not summ**e**ry)
Releated issue: https://github.com/jfrog/jfrog-client-go/issues/47
> fix: summary typo in error message

- utils/git.go
-----
On the git execution function, the `Dir` field, which indicates where the execution is running, was assigned mistakenly as the `.git` path.
This caused the git execution calls to run inside the` .git` folder and not the project folder.
> Fix git execution function wrong path assignment

- go.mod
- go.sum
-----
Depends on: 
* https://github.com/jfrog/build-info-go/pull/85
* https://github.com/jfrog/jfrog-cli-core/pull/406
* https://github.com/jfrog/jfrog-cli/pull/1552
> Duplicate build-info's artifacts are counted by their paths instead of their names

- .github/workflows/tests.yml
> Fix CLI_PIPE_ACCESS_TOKE typo on github secrets

- artifactory/services/utils/properties.go
- artifactory/services/utils/properties_test.go
-----
Fixes https://github.com/jfrog/jfrog-cli/issues/1587
Properties value can now contain characters '=' and ';' .
In case of ';' character in the value - user should use a backslash prefix and write ';' .
> Bugfix: Upload with target-prop's value contain special characters

- README.md
- artifactory/emptymanager.go
- artifactory/manager.go
- artifactory/services/system.go
- tests/artifactorysystem_test.go
-----
Add GetRunningNodes API to retrieve all running nodes' names in a cluster.
> Add GetRunningNodes API

- artifactory/services/utils/storageutils.go
- artifactory/services/utils/storageutils_test.go
- tests/artifactorystorage_test.go
-----
The storage info test fails occasionally because of a race between the
refresh and the subsequent call to fetch the storage information. In
some cases, the storage refresh has not completed before the request to
fetch the storage information occurs.
This change adds a loop with a timeout to the test to wait until the
repository is listed in the storage information before continuing to
assert the test statements.
> Fix flaky StorageInfo test

- README.md
- artifactory/emptymanager.go
- artifactory/manager.go
- artifactory/services/utils/aqlquerybuilder.go
- auth/cert/sslutils_default.go
- auth/cert/sslutils_windows.go
- go.mod
- go.sum
- tests/artifactorystorage_test.go
- utils/io/fileutils/files.go
-----
Depends on: https://github.com/jfrog/build-info-go/pull/93
* Currently, the get storage info API gets a "refresh" boolean. Triggering a refresh is an asynchronous operation and therefore there is no reason to trigger it right before the "get".
* Since we already break the API, I changed StorageInfo -> GetStorageInfo
* Fix storageInfoTest to allow it to run on SaaS environment.
* Remove IsStringInSlice and use the one in the build-info-go
> Separate storage info calc and get

- README.md
- tests/artifactorypermissiontarget_test.go
-----
The example for creating a permission target in the documentation
creates a segfault when executed. This change corrects the example code
and introduces a test which executes what the example would do.
Fixes: https://github.com/jfrog/jfrog-client-go/issues/543
> Correct segfault in example permission target code

- artifactory/services/utils/properties.go
- artifactory/services/utils/properties_test.go
-----
When testing, it is useful to be able to have some predictability in the
way that properties are encoded to a string. Since the properties struct
is currently backed by a map, the order that it is rendered to a string
is not predictable.
This change sorts the keys before rendering to a string. The items in
the arrays (the values in the map) are considered to be ordered and
hence are not sorted.
Feature Request: https://github.com/jfrog/jfrog-client-go/issues/549
> Encode properties in predictable order

- .github/workflows/tests.yml
make all jobs depend on the Go-lint job so it is the only job
that needs to check for the 'safe to test' label and can now safely remove it.
-----
> Unlabel safe to test automatically  

- README.md
- artifactory/emptymanager.go
- artifactory/manager.go
- artifactory/services/system.go
- tests/artifactorysystem_test.go
-----
Make DeactivateKeyEncryption return (wasEncrypted bool, err error). This change is needed to know whether we should encrypt after decrypting during the `jf rt transfer-config` command.
> Make DeactivateKeyEncryption return wasEncrypted

- http/httpclient/client.go
- utils/retryexecutor.go
- utils/retryexecutor_test.go
-----
Allow providing the context to the retry executor to allow canceling.
> Allow stopping retry executor

- artifactory/services/utils/deleteutils.go
- artifactory/services/utils/searchutil.go
- artifactory/services/utils/tests/testdata/candidate_dirs_to_be_deleted_results.json
-----
Issue:`Sync-delete` logic fails to filter out folders that should not be deleted. As a result, folders that start with lowercase are being deleted.
Part of: https://github.com/jfrog/jfrog-cli/pull/1681
> Sync-deletes - The wrong folders are deleted when uploading files with uppercase names

- xray/services/report.go
The current incorrect location creates a xray report that includes all the artifacts in a repo. See https://www.jfrog.com/confluence/display/JFROG/Xray+REST+API#XrayRESTAPI-GenerateVulnerabilitiesReport for reference
-----
> Generate Vulnerabilities Report - correct the location of key "include_path_pattern"

- distribution/services/deleteremote.go
- distribution/services/distribute.go
- utils/retryexecutor.go
- utils/retryexecutor_test.go
-----
In addition, fix distribute sync retries calculation.
> Return error on retry executor timeout

- artifactory/services/remoterepository.go
- tests/artifactoryremoterepository_test.go
> Add external dependencies rewrite parameters for helm remote repos

- artifactory/services/fspatterns/utils.go
- artifactory/services/fspatterns/utils_test.go
- artifactory/services/upload.go
- artifactory/services/upload_test.go
- artifactory/services/utils/artifactoryutils.go
- artifactory/services/utils/artifactoryutils_test.go
- tests/artifactoryupload_test.go
-----
The exclude pattern isn't behaving as expected. It doesn't respect the directory itself and exclude it even if it shouldn't.
For example:
<p>&nbsp;</p>
<div class="table-wrap">
Exclude Pattern | Expected behaviour | Actual behaviour
-- | -- | --
testdir/** | Should upload an empty folder | Everything is excluded, folder, files etc. Nothing gets uploaded
testdir** | Should match the behaviour of testdir/** | Everything is excluded, folder, files etc. Nothing gets uploaded
</div>
The root cause of this bug hides here :
```
if taskData.isDir && taskData.uploadParams.IsIncludeDirs() && !taskData.isSymlinkFlow {
if taskData.path != "." && (taskData.index == 0 || !utils.IsSubPath(taskData.paths, taskData.index, fileutils.GetFileSeparator())) {
uploadData.IsDir = true
} else {
return nil
} …
```
> Upload - Take into account the repository name with exclude pattern and include directory flags

- xray/services/scan.go
-----
Add 'other_component_ids' populated by the Xray indexer in the `jf scan` command for Debian.
> Add other_component_ids to /graph/scan API

- auth/authutils.go
- auth/authutils_test.go
> Add util to extract the subject from JWT tokens

- xray/services/scan.go
- xray/services/scan_test.go
- xray/services/utils/graph.go
> Fix flatten graph to cover node twice when needed.

- utils/io/content/contentwriter.go
-----
To enable immediate reading of the generated file, it is advisable to flush the Content Writer before closing it. This can be achieved by invoking the Sync() method on the Content Writer file. Once the content is flushed, the writer can be closed using the close() method. Performing these actions in sequence ensures that any buffered content is immediately written to the file, allowing for seamless reading or subsequent operations on the file, such as moving it.
For example, in the following code snippet, we close the Content Writer and then promptly move the file:
https://github.com/jfrog/jfrog-cli-core/blob/v2.35.0/artifactory/commands/transferfiles/errorshandler.go#L244
> Flush the Content Writer before closing

- artifactory/services/props.go
- artifactory/services/storage.go
-----
Cleaning relative paths (removing dot-dots) before joining them to Artifactory storage API URL.
> Clean relative paths in storage APIs

- http/httpclient/client.go
> Fix typo when using an API key as access token

- artifactory/services/gitlfsclean_test.go
- artifactory/services/go/go_test.go
- pipelines/services/run.go
- pipelines/services/syncstatus.go
- utils/tests/utils.go
> Fix gosec issues

- auth/authutils.go
- auth/servicedetails.go
> Reduce refreshing threshold for platform access token

- README.md
- access/manager.go
- artifactory/manager.go
- auth/servicedetails.go
- config/config.go
- config/configbuilder.go
- distribution/manager.go
- http/httpclient/clientBuilder.go
- http/jfroghttpclient/clientbuilder.go
- lifecycle/manager.go
- pipelines/manager.go
- tests/timeout_test.go
- utils/io/httputils/httpclient.go
- utils/tests/utils.go
- xray/manager.go
-----
* Rename HttpTimeout -> DialTimeout.
* Allow configuring "OverallRequestTimeout" to all requests. This timeout is the total time between the request and the response. It has no timeout by default.
> Support overall request timeout in all services

- artifactory/services/system.go
- distribution/services/version.go
- http/httpclient/client.go
- pipelines/services/system.go
- xray/services/entitlements.go
- xray/services/scan.go
- xray/services/version.go
> Improve JFrog platform get version error logs

- .github/workflows/analysis.yml
- artifactory/services/download.go
-----
Fix https://github.com/jfrog/jfrog-cli/issues/2260
Bypass archive inspection is ignored in chunked downloads.
> Bypass archive inspection is ignored

- http/httpclient/client.go
- utils/usage/reportusage.go
-----
Try to send usage reports to ecosystem service only once.
> Remove ecosystem usage report retry

- artifactory/services/utils/aqlquerybuilder.go
- artifactory/services/utils/aqlquerybuilder_test.go
- tests/artifactoryaql_test.go
- tests/jfrogclient_test.go
- tests/utils_test.go
- tests/xraybinmgr_test.go
- tests/xraywatch_test.go
-----
Create CreateAqlQueryForBuildInfo, which retrieves build information and generates an AQL query to return the SHA1 and MD5 checksums of the build-info.json file.
> New AQL query for build-info json

- http/httpclient/client.go
-----
HTTP responses might come back with a 429 error code, indicating "Too many requests." To help the client handle these errors better, we could enable retries.
> Retry HTTP requests when receiving 429

- artifactory/services/utils/specutils.go
- distribution/services/utils/distributionutils.go
- distribution/services/utils/releasebundlebody.go
- lifecycle/services/distribute.go
- tests/distribution_test.go
- utils/distribution/utils.go
- utils/distribution/utils_test.go
-----
Added support of "mappings" property to file spec in order to have the ability to control where to distribute the artifacts that are being added dynamically when using AQL in the release bundle that is being created.
When looking for docker artifacts using AQL, the release bundle also includes, in the distribution server backend, all the layers for a manifest.json and all of the manifest.json files and their layers if its a list.manifest.json
From now on the "mappings" will take affect on those none specified added manifests and layers and will allow the users a native way of creating the file spec for distribution commands.
FYI This couldn't be achieved using "target" for the list.manifest.json example.
> Support for Distribution path mapping with AQL

- xray/services/utils/graph.go
> Graph Scan internal API - New GraphNode field added to GraphNode

- xray/services/scan.go
-----
Adding back multi_scan_id to scan params for sca scan flow (xsc is expecting the multi_scan_id as query param).
PR for jfrog-cli-security for test purposes:
https://github.com/jfrog/jfrog-cli-security/pull/15
> Add multi_scan_id to scan params for sca scan flow

- README.md
- lifecycle/manager.go
- lifecycle/services/create.go
- lifecycle/services/delete.go
- lifecycle/services/operation.go
- lifecycle/services/promote.go
-----
Breaking changes:
- Changed signature of creation and promotion services.
- Removed the `overwrite_existing_artifacts` promotion option that has been decommissioned as of 7.75.0 (both from UI and API).
Improvement:
- Support for include/exclude repositories in release bundle promotion.
> Artifactory Release Lifecycle Management - Modify release bundle promotion properties

- README.md
- lifecycle/services/create.go
- pipelines/manager.go
- pipelines/services/integration.go
- tests/pipelinesintegrations_test.go
> Added a Pipelines API to give original integrations response without unmarshalling

- artifactory/services/utils/multipartupload.go
- artifactory/services/utils/multipartupload_test.go
-----
* Use `X-JFrog-Route-To` header instead of `X-Artifactory-Node-Id`.
* If the system receives a "service unavailable" error (status code 503) when checking the upload status using the API call `GET /api/v1/uploads/status`, the completion process will be retried on a different node.
> Tweak multipart upload polling

- artifactory/services/utils/multipartupload.go
- artifactory/services/utils/multipartupload_test.go
> Multipart upload - Fix empty nodeId response in completeMultipartUpload

- http/httpclient/client.go
> Support attaching Uber Trace ID to every request

- lifecycle/services/status.go
-----
The new status was introduced in the latest Artifactory version.
> Support Started Status for Release Bundle Creation

- auth/authutils.go
- auth/authutils_test.go
-----
Fix https://github.com/jfrog/setup-jfrog-cli/issues/146.
Previously, we assumed all JWT tokens followed this **subject** structure:
```
jfac@<some-characters>/users/<user-name>
```
However, OIDC tokens with group scopes might follow this **subject** structure instead:
```
<provider-name>/<identity-mapping>
```
This structure can serve as a standard username.
> Fix username extraction on OIDC tokens with a group scope

- http/httpclient/client.go
`httpclient.HttpClient.UploadFileFromReader()` used to not to close the HTTP response body when the status code is unexpected. The defer block for this should be appended right after the HTTP call is made.
-----
> Fix to close response body before status check

- artifactory/services/upload.go
- artifactory/services/utils/artifactoryutils.go
- artifactory/services/utils/multipartupload.go
- artifactory/services/utils/multipartupload_test.go
-----
Add the `X-Checksum-Deploy-Token` header to the checksum deploy request after a multipart upload.
> Multipart upload - Set the the checksum deploy token

- utils/io/fileutils/files.go
- utils/io/fileutils/files_test.go
- utils/vcsdetails.go
This is an attempt to fix https://github.com/jfrog/jfrog-cli/issues/2442.
The PR adds a new `IsPathAccessible` API, in addition to the existing `IsPathExists` functions. This is because the existing `IsPathExists` returns `false` in case of any error that occurred while accessing the directory, and not only in the case that the directory doesn't exist.
The new `IsPathAccessible` returns `false` in case the directory exists, but the user doesn't have permissions to access it. The usage of the new API by the Artifactory Upload code flow is expected to resolve the above issue.
> Add and use a new IsPathAccessible API before accessing the .git dir

- tests/xraywatch_test.go
> Fixing failing TestXrayWatch testcases

- README.md
- artifactory/services/repositories.go
- artifactory/services/repositories_test.go
-----
With this PR, all repositories for a specific project can be retrieved. It uses the current GetAllRepositoriesFiltered function with the project key added as a parameter.
Fixes https://github.com/jfrog/jfrog-client-go/issues/812
> Add project key to GetAllRepositoriesFiltered

- artifactory/emptymanager.go
- artifactory/manager.go
- artifactory/services/upload.go
- artifactory/services/utils/multipartupload.go
- utils/utils.go
-----
- Due to Static Analysis update, this PR also introduces safe int to uint and int64 to uint64 conversions in the multipartupload code.
> Add "Fail Fast" flag for Upload Service

- artifactory/services/repositories.go
- utils/log/logger.go
- utils/log/logger_test.go
-----
Add option for the logger not to remove Emojis.
> Add option to allow Emojis in log output

- artifactory/services/download.go
- artifactory/services/utils/searchutil.go
- http/httpclient/client.go
- utils/io/fileutils/temp.go
Fix a bug where after a file is downloaded from Artifactory, there's one temporary file that remains in the OS temp dir. This fix removes this temporary file.
> Remove remaining temp file after Artifactory download

- lifecycle/services/export.go
Modify the logic of the code that waits for the distribution export to finish.
Instead of waiting of the a completion signal from the API, we're also waiting for the relative path to not be "" or "/"
> Fix the "Get Distribution Export" polling logic

- tests/xsc_test.go
- tests/xscanalyticsevent_test.go
- tests/xscconfigprofile_test.go
- tests/xsclogerrorevent_test.go
- xray/services/xsc/xsc.go
- xsc/manager.go
- xsc/service.go
- xsc/services/profile.go
-----
This Pr introduces a new endpoint service that gets a configuration profile by repo URL.
The former "GetConfigProfile" service was changed to "GetProfileByName"
tests were added + initXscTest func was altered to better check Xsc endpoints after Xsc migration to Xray
This PR is a recreation of: https://github.com/jfrog/jfrog-client-go/pull/1054
> Add implementations for new API: config profile with repository context

- jfconnect/manager.go
- jfconnect/services/metrics.go
* Fix the API endpoint.
* Improve the API to accept a struct instead of a JSON
> Internal API - Visibility System fix & improvements

- tests/xraypolicy_test.go
- tests/xraywatch_test.go
- xray/services/scan.go
- xray/services/utils/policybody.go
-----
This PR adds new fields into Policy related structs
> Adding fields to Policy struct to support skip not applicable

- README.md
- artifactory/emptymanager.go
- artifactory/manager.go
- artifactory/services/buildinfo.go
- artifactory/services/utils/artifactoryutils.go
- go.mod
- go.sum
- tests/artifactorybuilds_test.go
-----
Adds the response of the [Build Runs API](https://jfrog.com/help/r/jfrog-rest-apis/build-runs).
Depends on https://github.com/jfrog/build-info-go/pull/294
> Add Build Runs API

- utils/io/content/contentreader.go
**Enhance Retry Mechanism for Content Reader Closure in Downloads**
**Summary**:
This PR improves the reliability of the download process by introducing a retry mechanism when closing the contentReader. 
**Changes:**
Added a retry mechanism to handle potential failures when closing the contentReader in the download process.
-----
-----
> Added retry mechanism for close contentReader in download.

- README.md
> Add OIDC token exchange documentation

- README.md
- lifecycle/lifecycle_test.go
- lifecycle/manager.go
- lifecycle/services/annotate.go
> RTDEV-56127 - Support annotate command for release bundle

- README.md
- utils/utils.go
- xray/manager.go
- xray/services/buildscan.go
- xray/services/entitlements.go
- xray/services/scan.go
- xray/services/xsc/xsc.go
- xsc/services/analytics.go
- xsc/services/logerrorevent.go
- xsc/services/profile.go
- xsc/services/watch.go
-----
For some of the API's, if the access token is project-scoped, it is expected to pass the related project key as a query param in the URL endpoint
> Add project key param to Xray api

- README.md
- artifactory/services/utils/tests/xray/consts.go
- artifactory/services/utils/tests/xray/server.go
- tests/xrayartifact_test.go
- xray/manager.go
- xray/services/artifact.go
-----
Add new Get Artifact Scan Status API to Xray manager, following:
* https://jfrog.com/help/r/xray-rest-apis/artifact-scan-status
> Add Get Artifact Scan Status Xray API

- artifactory/services/utils/buildUrlWithEscapingSlash.go
Description:
Due to this https://github.com/jfrog/jfrog-client-go/pull/1130/files,
Build Promotion Failure Due to String Encoding as BuildUrlWithEscapingSlash.
Solution
Replace QueryEscape function to PathEscape, because QueryEscape does double encoding and when / present inside build name and number, due to which wrong URL are generating. So, we need to encode special characters only except /.
-----
> Updated encoding function

- README.md
- apptrust/apptrust_test.go
- apptrust/auth/apptrustdetails.go
- apptrust/manager.go
- apptrust/services/application.go
- apptrust/services/application_test.go
-----
Add Support for AppTrust Client Manager in client.
Add GetApplicationDetails API to go-client.
Add README section of AppTrust manager
> Add support for apptrust manager and getApplicationDetail API
